-- Coway B2B Auto-mailing 테이블 생성 스크립트
-- automail-guide.md Step 2-6에 정의된 테이블 구조

CREATE TABLE b2b_automail_dt (
    SEQ               BIGINT NOT NULL AUTO_INCREMENT COMMENT '순번',
    FORM_ID           VARCHAR(50) DEFAULT NULL COMMENT '양식 ID',
    AUTOMAILFLAG      VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '자동 발생 대상 Flag : SAP IF에서 조회해 옴.',
    STCD2             VARCHAR(11) DEFAULT NULL COMMENT '사업자번호',
    CUST_NM           VARCHAR(40) DEFAULT NULL COMMENT '사업자명',
    KUNNR             VARCHAR(10) DEFAULT NULL COMMENT '대표고객코드',
    ZGRPNO            BIGINT DEFAULT NULL COMMENT '묶음번호',
    ORDER_NO          VARCHAR(20) DEFAULT NULL COMMENT '주문번호',
    FXDAY             SMALLINT DEFAULT NULL COMMENT '발행일',
    EMAIL             VARCHAR(50) DEFAULT NULL COMMENT '이메일1',
    EMAIL2            VARCHAR(50) DEFAULT NULL COMMENT '이메일2',
    MAILDATA          TEXT DEFAULT NULL COMMENT '청구서생성데이터(json 포맷)',
    DT_CREATE_DATE    DATETIME DEFAULT NULL COMMENT '데이터수집일',
    FILE_CREATE_FLAG  VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '파일생성Flag : 첨부파일 생성 후 Y 업데이트',
    ORI_HTML_FILENM   VARCHAR(100) DEFAULT NULL COMMENT 'HTML파일명(원본)',
    CHG_HTML_FILENM   VARCHAR(100) DEFAULT NULL COMMENT 'HTML파일명(변환)',
    HTML_FILEPATH     VARCHAR(200) DEFAULT NULL COMMENT 'HTML 경로',
    ORI_EXCEL_FILENM  VARCHAR(100) DEFAULT NULL COMMENT 'EXCEL파일명(원본)',
    CHG_EXCEL_FILENM  VARCHAR(100) DEFAULT NULL COMMENT 'EXCEL파일명(변환)',
    EXCEL_FILEPATH    VARCHAR(200) DEFAULT NULL COMMENT 'EXCEL 경로',
    FILE_CREATE_DATE  DATETIME DEFAULT NULL COMMENT '파일생성일',
    UMS_CODE          VARCHAR(20) DEFAULT NULL COMMENT '메일발송결과코드',
    UMS_MSG           VARCHAR(100) DEFAULT NULL COMMENT '메일발송결과메세지',
    UMS_KEY           VARCHAR(20) DEFAULT NULL COMMENT 'UMS Key',
    DEL_FLAG          VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
    CREATE_ID         VARCHAR(50) DEFAULT NULL COMMENT '등록자',
    CREATE_DATE       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초 등록일',
    UPDATE_ID         VARCHAR(50) DEFAULT NULL COMMENT '수정자',
    UPDATE_DATE       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='B2B 자동메일 발송 대상 테이블';

-- 인덱스 생성 (성능 최적화)
CREATE INDEX idx_automail_stcd2_kunnr ON b2b_automail_dt(STCD2, KUNNR);
CREATE INDEX idx_automail_zgrpno ON b2b_automail_dt(ZGRPNO);
CREATE INDEX idx_automail_order_no ON b2b_automail_dt(ORDER_NO);
CREATE INDEX idx_automail_flag ON b2b_automail_dt(AUTOMAILFLAG, FILE_CREATE_FLAG, DEL_FLAG);
CREATE INDEX idx_automail_create_date ON b2b_automail_dt(DT_CREATE_DATE); 